OCAMLMAKEFILE = ../OCamlMakefile

RESULT = sme
SOURCES = \
  labels.ml \
  language.ml \
  auxfunctions.ml \
  storeaux.ml \
  store.ml \
  dom.ml \
  release.ml \
  exprsemantics.ml \
  semantics.ml \
  inputoutput.ml \
  starter.ml

OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)

